### ISSUE TITLE
Actions hasn't run in months

### ISSUE THREAD

**Issue by DragRedSim** [hugo19941994/auto-datfile-generator#31]
Looks like actions got disabled about eight months ago due to inactivity on the repo. Just a heads up, since there's been changes since then, but nothing actually run through actions!

**Comment by hugo19941994** [comment]
I reenabled them but something's wrong, if I have time i'll try to fix it

**Comment by DragRedSim** [comment]
Yep, looks like it’s not liking the fact that the Logiqx site is down.

**Comment by dantob** [comment]
You can cherry-pick https://github.com/dantob/auto-datfile-generator/commit/8f6ece4b65e9f49aa55da577da2d69b1f0ac5939 & https://github.com/dantob/auto-datfile-generator/commit/de9abbbdf63e8b72811400c6b02930201519e61a if you'd like, CI has been running in my repo okay up until two days ago. (or I can open a pull request)

I occasionally see redump fail from timeouts, but the CI is set up to continue on failure and still update the completed assets.

No-intro has again broken the download button 2 days ago, IDK if it's because of these scripts, but I've never had anyone reach out and ask for the CI rebuild frequency to be reduced.
